import { Controller, NextFunction, Request, Response } from "@lyra-js/core"

export class ExampleStaticController extends Controller {
  /**
   * Example JSON API endpoint using static method approach
   * This demonstrates returning JSON data from a traditional static controller method
   */
  static exampleRouteMethod(req: Request, res: Response, next: NextFunction) {
    try {
      const exampleItem = {
        id: 1,
        title: "Static Controller Method Example",
        content:
          "This response is generated by a static controller method. Static methods are the traditional approach for defining route handlers in LyraJS, registered manually in route files. This endpoint returns JSON data, making it suitable for REST APIs consumed by frontend applications or mobile apps."
      }

      return res.status(200).json({ message: "Item fetched successfully", exampleItem })
    } catch (error) {
      return next(error)
    }
  }

  /**
   * Example SSR endpoint using static method approach
   * This demonstrates server-side rendering with Controller.renderStatic()
   * The rendered HTML is sent directly to the browser
   */
  static async exampleSsrRouteMethod(req: Request, res: Response, next: NextFunction) {
    try {
      return await Controller.renderStatic(res, "ExampleRender.tsx", {
        title: "Server-Side Rendering with Static Controllers",
        content:
          "This page is rendered on the server using the Controller.renderStatic() method from a traditional static controller. The HTML is generated server-side and sent to your browser, providing faster initial page loads and better SEO. Static methods require manual route registration in your route files (e.g., src/router/routes/*.ts).",
        documentationUrl: "https://lyrajs.dev/"
      })
    } catch (error) {
      return next(error)
    }
  }
}
